events {
    worker_connections 128; # Increase if you expect high traffic.
}
http {
    upstream backend {
        server s0-n00.hpc.meduniwien.ac.at:5000;
        server s0-n01.hpc.meduniwien.ac.at:5000;
        server s0-n01.hpc.meduniwien.ac.at:5001;
        server s0-n01.hpc.meduniwien.ac.at:5002;
        # Add as many servers as you need
    }

    server {
        listen 5000; # Port to listen on

        location / {
            proxy_pass http://backend;
        }
    }
}
