anndata_label_name: natural_language_annotation
num_replicates: 5

paths:
  mixtral_model: ~/text-generation-webui/models/mixtral-8x7b-instruct-v0.1.Q5_K_M.gguf
  read_count_table: resources/{dataset}/read_count_table.h5ad
  raw_annotations: resources/{dataset}/annotations.tsv
  structured_annotations: results/{dataset}/annotations.json
  processed_annotations: results/{dataset}/processed_annotations.json
  processed_multi_annotations: results/{dataset}/processed_multi_annotations.json
  llava_pretrain_text_dataset: results/llava_pretrain_texts.json
  llava_finetune_text_dataset: results/llava_finetune_conversations.json
  llava_evaluation_text_dataset: results/llava_evaluation_conversations.json
  geneset_gmt: results/genesets/{library}.gmt
  gsva_results: results/{dataset}/gsva.parquet
  model_processed_dataset: results/{dataset}/{model}/full_output.npz
  llava_pretrained_model_dir: results/llava/pretrained/{base_model}__{model}/
  llava_finetuned_model_dir: results/llava/finetuned/{base_model}__{model}/
  full_dataset: results/{dataset}/full_data.h5ad
  llm_embeddings: results/{dataset}/llm_embeddings.npz  # deprecated
  rna_embeddings: results/{dataset}/rna_embeddings.npz  # deprecated
  enrichr_terms_json: resources/enrichr_terms/terms.json
  ensembl_gene_symbol_map: resources/ensembl_gene_symbol_map.csv
  jointemb_models: results/models/jointemb
  wandb_logs: results/wandb_logging
  datamodule_prepared_path: results/{dataset}/lightning-processed/{hash}.pt
  cache: results/cache  # overwritable with CELLWHISPERER_CACHE env
  cancer_gene_essentiality:
    ccle_expression: CCLE_RNAseq_genes_counts_20180929.gct.gz
    essential_genes: resources/cancer_gene_essentiality/CRISPRInferredCommonEssentials.csv
    nonessential_genes: resources/cancer_gene_essentiality/AchillesNonessentialControls.csv

datasets:
  - immgen
  - daniel
  - tabula_sapiens
  - tabula_sapiens_100_cells_per_type
  - archs4_metasra
  - development4s_raw
  - development4s_scvi
  # - perturbation_kaggle

retrieval_validation_sets:
  - immgen_deduplicated
  - daniel_strictly_deduplicated_dmis-lab_biobert-v1.1_CLS_pooling


model_name_path_map:
  geneformer: resources/geneformer-12L-30M
  biogpt: microsoft/biogpt
  bert: dmis-lab/biobert-v1.1
  scgpt: resources/scGPT_human
  cellwhisperer: 03jujd8s
    # poor choice with scgpt: 609rcmt4


genesets:
  - "Azimuth_2023"
  - "GO_Biological_Process_2023"
  - "GO_Cellular_Component_2023"
  - "GO_Molecular_Function_2023"
  - "OMIM_Expanded"
  - "PanglaoDB_Augmented_2021"
  - "Tabula_Sapiens"
  - "Cytopus_immune_identities"
  - "Cytopus_processes"



# Only used, if not dedicated hyperparameter config file is provided
SWEEP_HYPERPARAMETERS:
  method: random
  name: test_sweep
  metric:
    goal: minimize
    name: val_loss
  parameters:
    batch_size:
      values: [2, 4]
    trainer.fast_dev_run:
      values: [true]
