anndata_label_name: natural_language_annotation

paths:
  read_count_table: resources/{dataset}/read_count_table.h5ad
  raw_annotations: resources/{dataset}/annotations.tsv
  structured_annotations: results/{dataset}/annotations.json
  processed_annotations: results/{dataset}/processed_annotations.json
  full_dataset: results/{dataset}/full_data.h5ad
  llm_embeddings: results/{dataset}/llm_embeddings.npz
  rna_embeddings: results/{dataset}/rna_embeddings.npz
  enrichr_terms_json: resources/enrichr_terms/terms.json
  ensembl_gene_symbol_dict: resources/ensembl_gene_symbol_dict.csv
  jointemb_models: results/models/jointemb
  wandb_logs: results/wandb_logging
  datamodule_prepared_path: results/{dataset}/lightning-processed/inputs.pt

datasets:
  - immgen
  - daniel
