settings {
   pidfile    = "/tmp/lsyncd_single-cellm_home.pid",
   logfile    = "/tmp/lsyncd_single-cellm_home.log",
   statusFile = "/tmp/lsyncd_single-cellm_home.status",
   nodaemon   = false,
}


sync {
  default.rsync,
  source = "/home/moritz/Projects/single-cellm/",
  target = "moxps:/home/moritz/Projects/single-cellm/",
  delay = 3,
  exclude = { '.snakemake', 'conda', '.conda', '.venv', '.mypy_cache', 'wandb', 'artifacts', 'lightning_logs', 'build', "*.so", "__pycache__", ".#*", "node_modules", "resources", "results", "modules/cellxgene/client/node_modules", ".git"},
  rsync = {
    archive = true,
    compress = true
  },
  delete = false
}

