settings {
   pidfile    = "/tmp/lsyncd_cellwhisperer_home.pid",
   logfile    = "/tmp/lsyncd_cellwhisperer_home.log",
   statusFile = "/tmp/lsyncd_cellwhisperer_home.status",
   nodaemon   = false,
}


sync {
  default.rsync,
  source = "/home/moritz/Projects/cellwhisperer/",
  target = "moxps:/home/moritz/Projects/cellwhisperer/",
  delay = 3,
  exclude = {'.snakemake', 'conda', '.conda', '.venv', '.mypy_cache', 'wandb', 'artifacts', 'lightning_logs', 'build', "*.so", "__pycache__", ".#*", "node_modules", "resources", "results", "modules/cellxgene/client/node_modules", ".git", "modules/cellxgene/server/common/web"},
  rsync = {
    archive = true,
    compress = true
  },
  delete = false
}

