import subprocess

PROJECT_DIR = Path(subprocess.check_output("git rev-parse --show-toplevel", shell=True).decode("utf-8").strip())
configfile: PROJECT_DIR / "config.yaml"

CLIP_MODEL = config["model_name_path_map"]["cellwhisperer"]
LLAVA_BASE_MODEL = config["model_name_path_map"]["llava_base_llm"]

CELLTYPE_TERMS_DICT={  # consider moving to config
    "erythrocyte": "red blood cells",
    "erythrocyte": "erythrocyte",
    "nk cell": "Natural killer cells",
    "t cell": "T cells",
    "b cell": "B cells",
    "platelet": "blood platelets",
}

SCFMS = ["geneformer", "scgpt", "uce"]  # TODO add `cellwhisperer` and make sure it is translated to `cellwhisperer_clip_v1` everywhere. Or add the latter anyways

from notebooks.zero_shot_validation_scripts.utils import SUFFIX_PREFIX_DICT  # consider moving to config


GPU_TYPE = "a100"
# GPU_TYPE = "a100-sxm4-80gb"

include: "../shared/rules/dataset_processing.smk"
include: "rules/fig1_landscape_validation_ablation.smk"
include: "rules/fig2_embedding_validations.smk"
include: "rules/fig3_interactive_usecase_llm.smk"
include: "rules/fig4_colonic_epithelium.smk"
rule all:
    input:
        # Figure 1
        rules.geo_umap_plots.output.cluster_labeled.format(model=CLIP_MODEL),
        # Figure S1
        rules.final_model_retrieval_scores.output.barplot,
        rules.final_model_retrieval_scores.output.lineplot,
        rules.plot_ablation_wandb.output.all_models_comparison,  # Ablation study

        # Figure 2
        expand(rules.plot_confusion_matrix.output.confusion_matrix_plot,
               model=CLIP_MODEL,
               dataset=["tabula_sapiens", "tabula_sapiens_well_studied_celltypes"],  # TODO pancreas?
               metadata_col="celltype",
               normed=["normed", "raw"]),
        expand(rules.plot_term_search_results.output.umap_on_neighbors_celltype, celltype=CELLTYPE_TERMS_DICT.keys(), file_suffix=["png"], model="cellwhisperer_clip_v1"),
        [
            base_fn.format(dataset=dataset, model=CLIP_MODEL, metadata_col=metadata_col)
            for base_fn in [rules.plot_zero_shot_predictions_on_umap.output.result_dir, rules.plot_confidence_distributions.output.plot_dir]
            for dataset in ["tabula_sapiens", "pancreas"]  # TODO config["metadata_cols_per_zero_shot_validation_dataset"].keys()
            for model in [CLIP_MODEL]
            for metadata_col in config["metadata_cols_per_zero_shot_validation_dataset"][dataset]
        ],

        # LLM prediction
        expand(rules.aggregate_zero_shot_llm_property_predictions.output.aggregated_predictions,
               # metadata_col=list(set([v for l in config["metadata_cols_per_zero_shot_validation_dataset"].values() for v in l])),
               metadata_col=["Tissue", "celltype"],  # NOTE For cost-reasons we restricted to two properties for now.
               grouping=["by_cell", "by_class"]
               ),
        expand(rules.zero_shot_performance_macroavg.output.macroavg_summary_plot, model=CLIP_MODEL),
        expand(rules.zero_shot_performance_examples.output.per_class_examples_plot, model=CLIP_MODEL),
        expand(rules.aggregate_scfm_evaluations.output, training_options=TRAINING_OPTIONS, metric=["accuracy", "f1", "auroc"]),

        # Figure S2 (extended: embedding and gene set correlation analyses)
        expand(PROJECT_DIR / config["paths"]["gsva"]["correlation"], dataset=["human_disease"], model=CLIP_MODEL),  # NOTE: Can also be run for tabula_sapiens and for archs4_geo
        expand(rules.plot_joint_transcriptome_embedding_scib.output.integration_scores, dataset=["tabula_sapiens", "pancreas"]),

        # Figure S3 (LLM validations)
        expand(PROJECT_DIR / config["paths"]["llava"]["evaluation_results"] / "{plot_name}.svg",
               plot_name=["detailed", "perplexity_quantile"],
               dataset=["main", "main_top50genes", "tabula_sapiens_100_cells_per_type", "tabula_sapiens_100_cells_per_type_top50genes"],  # NOTE: these are evaluation datasets
               base_model=[LLAVA_BASE_MODEL],  # NOTE could test as well: "BioMistral-7B", "BioMistral-7B-DARE",
               model=[CLIP_MODEL, "geneformer"],
               prompt_variation=["with50topgenes", "without50topgenes"],
               ),
        expand(PROJECT_DIR / config["paths"]["llava"]["evaluation_results"] / "{plot_name}.svg",
               plot_name=["detailed", "perplexity_quantile"],
               dataset=["main", "tabula_sapiens_100_cells_per_type"],  # NOTE: these are evaluation datasets
               base_model=[LLAVA_BASE_MODEL, "Llama-3.1-8B-Instruct"],  # TODO add "Llama-3.3-70B-Instruct"
               model=["NONE"],
               prompt_variation=["with50topgenes"],
               ),

        # Figure 4
        expand(rules.bowel_disease_stem_cell_contribution.output.plot, target_cluster=["", "Cycling ileal epithelial precursor cells"]),

    default_target: True
