include: "../shared/config.smk"
include: "../shared/rules/dataset_processing.smk"
include: "rules/fig1_landscape_validation_ablation.smk"
include: "rules/fig2_embedding_validations.smk"
include: "rules/fig3_interactive_usecase_llm.smk"
include: "rules/fig4_colonic_epithelium.smk"
include: "rules/reviewer_response.smk"

rule all:
    input:
        # Figure 1
        rules.geo_umap_plots.output.cluster_labeled.format(model=CLIP_MODEL),
        # Figure S1
        rules.final_model_retrieval_scores.output.barplot,
        rules.final_model_retrieval_scores.output.lineplot,
        rules.plot_ablation_wandb.output.all_models_comparison,  # Ablation study

        # Figure 2
        expand(rules.plot_confusion_matrix.output.confusion_matrix_plot,
               model=CLIP_MODEL,
               dataset=["tabula_sapiens", "tabula_sapiens_well_studied_celltypes"],  # TODO pancreas?
               metadata_col="celltype",
               normed=["normed", "raw"]),
        expand(rules.zero_shot_performance_suppl_table.output.confusion_mtx_table, model=CLIP_MODEL),
        expand(rules.plot_term_search_results.output.umap_on_neighbors_celltype, celltype=config["celltype_terms"].keys(), file_suffix=["png"], model=CW_CLIP_MODELS),
        [
            base_fn.format(dataset=dataset, model=CLIP_MODEL, metadata_col=metadata_col)
            for base_fn in [rules.plot_zero_shot_predictions_on_umap.output.result_dir, rules.plot_confidence_distributions.output.plot_dir]
            for dataset in ["tabula_sapiens", "pancreas"]  # TODO config["metadata_cols_per_zero_shot_validation_dataset"].keys()
            for model in [CLIP_MODEL]
            for metadata_col in config["metadata_cols_per_zero_shot_validation_dataset"][dataset]
        ],

        # Text-only LLM prediction
        expand(rules.aggregate_zero_shot_llm_property_predictions.output.aggregated_predictions,
               metadata_col=list(set([v for l in config["metadata_cols_per_zero_shot_validation_dataset"].values() for v in l])),
               # metadata_col=["Tissue", "celltype", "organ_tissue", "Disease_subtype"],  # same same TODO delete
               grouping=["by_cell", "by_class"]
               ),
        expand(rules.zero_shot_performance_macroavg.output.macroavg_summary_plot, model=CLIP_MODEL),
        expand(rules.zero_shot_performance_examples.output.per_class_examples_plot, model=CLIP_MODEL),
        expand(rules.aggregate_scfm_evaluations.output, training_options=TRAINING_OPTIONS, metric=["accuracy", "f1", "auroc"]),

        # Figure S2 (extended: embedding and gene set correlation analyses)
        expand(PROJECT_DIR / config["paths"]["gsva"]["correlation"], dataset=["human_disease"], model=CLIP_MODEL),  # NOTE: Can also be run for tabula_sapiens and for archs4_geo
        expand(rules.plot_joint_transcriptome_embedding_scib.output.integration_scores, dataset=["tabula_sapiens", "pancreas"]),

        rules.fig3_llava_ppl_all.input,

        rules.fig4_all.input,

        # Reviewer response letter
        rules.plot_query_variant_cell_matching.output.plot.format(model=config["model_name_path_map"]["cellwhisperer_geneformer"]),

    default_target: True
