"""
CellWhisperer LLM validations based on

- perplexity

Next better evaluations could include

- how many of the top 100 genes can it recover?
- how well does it reproduce pathways?
"""

import pandas as pd


scattergather:  # same as in llava pipeline
    split=128

# This list is generated by the llava pipeline and, for convenience, tracked as part of the source code
ARCHS4_GSVA_SAMPLES = pd.read_csv(PROJECT_DIR / "src/llava/gsva_samples.csv", header=None).iloc[:, 0]

NUM_COMPLEX_SAMPLES = 5000
NUM_DETAILED_SAMPLES = 10000
CONVERSATION_START = NUM_COMPLEX_SAMPLES + NUM_DETAILED_SAMPLES
COMPLEX_SAMPLES = ARCHS4_GSVA_SAMPLES.to_list()[:NUM_COMPLEX_SAMPLES]
DETAILED_SAMPLES = ARCHS4_GSVA_SAMPLES.to_list()[NUM_COMPLEX_SAMPLES:CONVERSATION_START]


include: "llm_judge.smk"

def top_genes_fn(wildcards):
    if wildcards.dataset in ["main", "main_top50genes"]:
        return [ancient(rules.compute_top_genes.output.top_genes.format(dataset=dataset)) for dataset in ["cellxgene_census", "archs4_geo"]]
    else:
        return [rules.compute_top_genes.output.top_genes.format(dataset=wildcards.dataset.replace("_top50genes", ""))]

rule llava_evaluation_topgenes_dataset:
    input:
        dataset=lambda wildcards: str(PROJECT_DIR / config["paths"]["llava"]["evaluation_text_dataset"]).format(dataset=wildcards.dataset.replace("_top50genes", "")),
        top_genes=top_genes_fn
    output:
        evaluation_dataset=PROJECT_DIR / config["paths"]["llava"]["evaluation_text_dataset"],
    params:
        question=config["llava_eval"]["question_topgenes"],
        response_prefix=config["llava_eval"]["response_prefix_topgenes"],
        top_n_genes=50,
    resources:
        mem_mb=90000,
    conda:
        "cellwhisperer"
    notebook:
        "../notebooks/llava_evaluation_topgenes_dataset.py.ipynb"

rule llava_evaluation_perplexity:
    """
    """
    input:
        llava_model=lambda wildcards:
            ancient(PROJECT_DIR / config["paths"]["llava"]["finetuned_model_dir"].format(base_model=wildcards.base_model, model=wildcards.model))
            if wildcards.model != "NONE" else
            PROJECT_DIR / "resources" / wildcards.base_model,
        evaluation_dataset=PROJECT_DIR / config["paths"]["llava"]["evaluation_text_dataset"],
        # image_data=rules.process_full_dataset.output.model_outputs.format(dataset="{dataset}", model=config["model_name_path_map"]["cellwhisperer"]),
        image_data=lambda wildcards: rules.combine_processed_data.output.combined.format(model=wildcards.model.replace("NONE", "cellwhisperer_clip_v1")),  # For NONE, we don't need any image_data, but we do need to provide a file
        top_genes=top_genes_fn  # only required for `prompt_variation="with50topgenes"`. not sure if `ancient` is correct
    conda:
        "llava"
    output:
        all_perplexities=PROJECT_DIR / config["paths"]["llava"]["evaluation_results"] / "all_perplexities.csv",
    params:
        num_projector_tokens=int(config["llava_projector_type"].split("_")[1].strip("t")),
        background_shuffle=lambda wildcards: {"with50topgenesshuffled": "genesshuffled", "with50topgenesresponsepermuted": "responsepermuted", "without50topgenesresponsepermuted": "responsepermuted"}.get(wildcards.prompt_variation, "transcriptome"),
        num_negatives=30,
        model_layer_selector=-1,
        pre_prompt_topgenes=lambda wildcards: config["llava_eval"]["pre_prompt_topgenes"] if "with50topgenes" in wildcards.prompt_variation else None,
        top_n_genes=50,
        is_multimodal=lambda wildcards: not (wildcards.model == "NONE" or "noembedding" in wildcards.prompt_variation)
    resources:
        mem_mb=100000,
        slurm=lambda wildcards: slurm_gres(
            "large",
            num_gpus={LLAVA_BASE_MODEL: 1, "Llama-3.1-8B-Instruct": 1, "Llama-3.3-70B-Instruct": 3}[wildcards.base_model]
        )
    log:
        notebook="logs/llava_evaluation_perplexity/{dataset}_{base_model}_{model}_{prompt_variation}.ipynb",
        log="logs/llava_evaluation_perplexity/{dataset}_{base_model}_{model}_{prompt_variation}.log"
    threads: 16
    notebook:
        "../notebooks/llava_evaluation_perplexity.py.ipynb"

rule llava_evaluation_perplexity_plots:
    """
    """
    input:
        all_perplexities=rules.llava_evaluation_perplexity.output.all_perplexities,
        mpl_style=ancient(PROJECT_DIR / config["plot_style"])
    output:
        log_perplexity_ratio=PROJECT_DIR / config["paths"]["llava"]["evaluation_results"] / "log_mean_perplexity.ratio",  # smaller is better log(ppl_real/ppl_neg_control)
        comparison_plot=PROJECT_DIR / config["paths"]["llava"]["evaluation_results"] / "perplexity_quantile.svg",  # barplot
        detailed_plot=PROJECT_DIR / config["paths"]["llava"]["evaluation_results"] / "detailed.svg",  # barplot
        full_supp_table=PROJECT_DIR / config["paths"]["llava"]["root"] / "{dataset}" / "{base_model}__{model}" / "quantile_stats_{prompt_variation}.xlsx"
    params:
        plot_celltypes=config["top20_lung_liver_blood_celltypes"],
        response_prefix=lambda wildcards: config["llava_eval"]["response_prefix_{}".format(
            "topgenes" if "_top50genes" in wildcards.dataset else "celltype")]
    conda:
        "llava"  # newer version of pandas in this env
    log:
        notebook="logs/llava_evaluation_perplexity_plots/{dataset}_{base_model}_{model}_{prompt_variation}.ipynb"
    notebook:
        "../notebooks/llava_evaluation_perplexity_plots.py.ipynb"


def input_configurations(wildcards):
    if wildcards.plot_type == "llava_cw_vs_geneformer":
        return [
            {"base_model": LLAVA_BASE_MODEL, "model": "geneformer", "prompt_variation": "without50topgenes"},
            {"base_model": LLAVA_BASE_MODEL, "model": "geneformer", "prompt_variation": "with50topgenes"},
            {"base_model": LLAVA_BASE_MODEL, "model": "geneformer", "prompt_variation": "without50topgenesresponsepermuted"},
            {"base_model": LLAVA_BASE_MODEL, "model": "cellwhisperer_clip_v1", "prompt_variation": "without50topgenes"},
            {"base_model": LLAVA_BASE_MODEL, "model": "cellwhisperer_clip_v1", "prompt_variation": "with50topgenes"},
            {"base_model": LLAVA_BASE_MODEL, "model": "cellwhisperer_clip_v1", "prompt_variation": "without50topgenesresponsepermuted"},
        ]
    if wildcards.plot_type == "gene_predictability":
        if not wildcards.dataset.endswith("top50genes"):
            print("gene_predictability is only well-defined for top_50gene dataset")

        return [
            {"base_model": LLAVA_BASE_MODEL, "model": "NONE", "prompt_variation": "without50topgenes"},  #  negative control
            {"base_model": LLAVA_BASE_MODEL, "model": "cellwhisperer_clip_v1", "prompt_variation": "with50topgenes"},  # positive control
            {"base_model": LLAVA_BASE_MODEL, "model": "cellwhisperer_clip_v1", "prompt_variation": "without50topgenes"},  # normal performance
            {"base_model": LLAVA_BASE_MODEL, "model": "cellwhisperer_clip_v1", "prompt_variation": "without50topgenesresponsepermuted"},  # different background distribution
            {"base_model": LLAVA_BASE_MODEL, "model": "cellwhisperer_clip_v1", "prompt_variation": "with50topgenesshuffled"},  # confusing the model with wrong input gene order
        ]
    if wildcards.plot_type == "text_only_vs_cw":
        if wildcards.dataset.endswith("top50genes"):
            print("text_only_vs_cw doesn't make sense with top50genes datasets")
        return [
            {"base_model": LLAVA_BASE_MODEL, "model": "NONE", "prompt_variation": "without50topgenes"},  # neg control

            {"base_model": LLAVA_BASE_MODEL, "model": "NONE", "prompt_variation": "with50topgenes"},  # pos control
            {"base_model": "Llama-3.1-8B-Instruct", "model": "NONE", "prompt_variation": "with50topgenes"},
            {"base_model": "Llama-3.3-70B-Instruct", "model": "NONE", "prompt_variation": "with50topgenes"},
            {"base_model": LLAVA_BASE_MODEL, "model": "cellwhisperer_clip_v1", "prompt_variation": "without50topgenes"},

            # TODO put this into a second axis (due to shifted value range)
            {"base_model": LLAVA_BASE_MODEL, "model": "NONE", "prompt_variation": "with50topgenesresponsepermuted"},
            {"base_model": "Llama-3.1-8B-Instruct", "model": "NONE", "prompt_variation": "with50topgenesresponsepermuted"},
            {"base_model": "Llama-3.3-70B-Instruct", "model": "NONE", "prompt_variation": "with50topgenesresponsepermuted"},
            {"base_model": LLAVA_BASE_MODEL, "model": "cellwhisperer_clip_v1", "prompt_variation": "without50topgenesresponsepermuted"},
        ]
    if wildcards.plot_type == "cw_preprompt_useless":
        if wildcards.dataset.endswith("top50genes"):
            print("cw_preprompt_useless doesn't make sense with top50genes datasets")
        return [
            # {"base_model": LLAVA_BASE_MODEL, "model": "NONE", "prompt_variation": "without50topgenes"},  # neg control
            # {"base_model": LLAVA_BASE_MODEL, "model": "NONE", "prompt_variation": "with50topgenesshuffled"},  # semi-neg control
            # {"base_model": LLAVA_BASE_MODEL, "model": "NONE", "prompt_variation": "with50topgenes"},  # pos control
            {"base_model": LLAVA_BASE_MODEL, "model": "cellwhisperer_clip_v1", "prompt_variation": "with50topgenesnoembedding"},  # Baseline: CW with only top 50 genes
            {"base_model": LLAVA_BASE_MODEL, "model": "cellwhisperer_clip_v1", "prompt_variation": "without50topgenes"},
            {"base_model": LLAVA_BASE_MODEL, "model": "cellwhisperer_clip_v1", "prompt_variation": "with50topgenes"},  # show that adding 50 top genes doesn't help (much)
            # {"base_model": LLAVA_BASE_MODEL, "model": "cellwhisperer_clip_v1", "prompt_variation": "with50topgenesshuffled"},  # no negative effect by shuffling the genes <- could show this alone

            # {"base_model": LLAVA_BASE_MODEL, "model": "NONE", "prompt_variation": "with50topgenesresponsepermuted"},
            # {"base_model": LLAVA_BASE_MODEL, "model": "cellwhisperer_clip_v1", "prompt_variation": "without50topgenesresponsepermuted"},
        ]


rule llava_comparative_perplexity_plots:
    """
    General comparative plots for llava perplexity analysis

    Relative plots: compare pairwise and show which one is better how often (matrix)

    See notebook for by-celltype plot (only TabSap)

    TODO make sure they have all been regenerated at some point..
    """
    input:
        perplexities=lambda wildcards: [
            rules.llava_evaluation_perplexity.output.all_perplexities.format(**x, dataset=wildcards.dataset)
            for x in input_configurations(wildcards)
        ],
        evaluation_dataset=PROJECT_DIR / config["paths"]["llava"]["evaluation_text_dataset"],
        mpl_style=ancient(PROJECT_DIR / config["plot_style"]),
    output:
        individual_performances=PROJECT_DIR / "results/plots/llava/{dataset}/ppl_model_comparison/{plot_type}/{plot_metric}_individual.svg",
        relative_performances=PROJECT_DIR / "results/plots/llava/{dataset}/ppl_model_comparison/{plot_type}/{plot_metric}_relative.svg",
    params:
        comparison_sequence=input_configurations,
        plot_celltypes=config["top20_lung_liver_blood_celltypes"],
        response_prefix=lambda wildcards: config["llava_eval"]["response_prefix_{}".format(
            "topgenes" if "_top50genes" in wildcards.dataset else "celltype")],
        plot_type="violin",
    resources:
        mem_mb=50000,
    conda:
        "llava"
    notebook:
        "../notebooks/llava_comparative_perplexity_plots.py.ipynb"

rule fig3_llava_ppl_all:
    input:
        expand(
            rules.llava_comparative_perplexity_plots.output.individual_performances,
            plot_metric=["log2_correct_ppl", "log2_ppl_ratio"],
            plot_type=["llava_cw_vs_geneformer", "text_only_vs_cw", "cw_preprompt_useless"],
            dataset=["main", "tabula_sapiens_100_cells_per_type"],  # only 'normal' datasets
        ),
        expand(
            rules.llava_comparative_perplexity_plots.output.individual_performances,
            plot_metric=["log2_correct_ppl", "log2_ppl_ratio"],
            plot_type=["llava_cw_vs_geneformer", "gene_predictability"],
            dataset=["main_top50genes", "tabula_sapiens_100_cells_per_type_top50genes"],  # only top50 datasets
        ),

        # Pre-revision
        expand(PROJECT_DIR / config["paths"]["llava"]["evaluation_results"] / "{plot_name}.svg",
               plot_name=["detailed", "perplexity_quantile"],
               dataset=["main", "tabula_sapiens_100_cells_per_type"],  # NOTE: these are llava evaluation datasets
               base_model=[LLAVA_BASE_MODEL],
               model=[config["model_name_path_map"]["cellwhisperer_geneformer"], "geneformer"],  # config["model_name_path_map"]["cellwhisperer_uce"], "uce"
               prompt_variation=["with50topgenes", "without50topgenes", "with50topgenesshuffled"],
               ),

        # top 50 genes prediction
        expand(PROJECT_DIR / config["paths"]["llava"]["evaluation_results"] / "{plot_name}.svg",
               plot_name=["detailed", "perplexity_quantile"],
               dataset=["main_top50genes", "tabula_sapiens_100_cells_per_type_top50genes"],
               base_model=[LLAVA_BASE_MODEL],
               model=[config["model_name_path_map"]["cellwhisperer_geneformer"], "geneformer"],  # config["model_name_path_map"]["cellwhisperer_uce"], "uce"],
               prompt_variation=["without50topgenes", "without50topgenesresponsepermuted"],
               ),
        # text-only (non-finetuned) LLMs
        expand(PROJECT_DIR / config["paths"]["llava"]["evaluation_results"] / "{plot_name}.svg",
               plot_name=["detailed", "perplexity_quantile"],
               dataset=["main", "tabula_sapiens_100_cells_per_type"],
               base_model=[LLAVA_BASE_MODEL, "Llama-3.1-8B-Instruct", "Llama-3.3-70B-Instruct"],
               model=["NONE"],
               prompt_variation=["with50topgenes", "with50topgenesshuffled"],
               ),

        # judge
        rules.llava_eval_gpt4_review_summarize.output.overview_plot.format(base_model=LLAVA_BASE_MODEL, model=CLIP_MODEL, prompt_variation="llm_judge", dataset="main")
