"""
CellWhisperer LLM validations based on

- perplexity

Next better evaluations could include

- how many of the top 100 genes can it recover?
- how well does it reproduce pathways?
"""

import pandas as pd


scattergather:  # same as in llava pipeline
    split=128

# This list is generated by the llava pipeline and, for convenience, tracked as part of the source code
ARCHS4_GSVA_SAMPLES = pd.read_csv(PROJECT_DIR / "src/llava/gsva_samples.csv", header=None).iloc[:, 0]

NUM_COMPLEX_SAMPLES = 5000
NUM_DETAILED_SAMPLES = 10000
CONVERSATION_START = NUM_COMPLEX_SAMPLES + NUM_DETAILED_SAMPLES
COMPLEX_SAMPLES = ARCHS4_GSVA_SAMPLES.to_list()[:NUM_COMPLEX_SAMPLES]
DETAILED_SAMPLES = ARCHS4_GSVA_SAMPLES.to_list()[NUM_COMPLEX_SAMPLES:CONVERSATION_START]

def top_genes_fn(wildcards):
    if wildcards.dataset in ["main", "main_top50genes"]:
        return [ancient(rules.compute_top_genes.output.top_genes.format(dataset=dataset)) for dataset in ["cellxgene_census", "archs4_geo"]]
    else:
        return [rules.compute_top_genes.output.top_genes.format(dataset=wildcards.dataset.replace("_top50genes", ""))]

rule llava_evaluation_topgenes_dataset:
    input:
        dataset=lambda wildcards: str(PROJECT_DIR / config["paths"]["llava"]["evaluation_text_dataset"]).format(dataset=wildcards.dataset.replace("_top50genes", "")),
        top_genes=top_genes_fn
    output:
        evaluation_dataset=PROJECT_DIR / config["paths"]["llava"]["evaluation_text_dataset"],
    params:
        question=config["llava_eval"]["question_topgenes"],
        response_prefix=config["llava_eval"]["response_prefix_topgenes"],
        top_n_genes=50,
    resources:
        mem_mb=90000,
    conda:
        "cellwhisperer"
    notebook:
        "../notebooks/llava_evaluation_topgenes_dataset.py.ipynb"

rule llava_evaluation_perplexity:
    """
    """
    input:
        llava_model=lambda wildcards:
            ancient(PROJECT_DIR / config["paths"]["llava"]["finetuned_model_dir"].format(base_model=wildcards.base_model, model=wildcards.model))
            if wildcards.model != "NONE" else
            ancient(PROJECT_DIR / "resources" / wildcards.base_model),
        evaluation_dataset=PROJECT_DIR / config["paths"]["llava"]["evaluation_text_dataset"],
        # image_data=rules.process_full_dataset.output.model_outputs.format(dataset="{dataset}", model=config["model_name_path_map"]["cellwhisperer"]),
        image_data=rules.combine_processed_data.output.combined.format(model=config["model_name_path_map"]["cellwhisperer"]),
        top_genes=top_genes_fn  # only required for `prompt_variation="with50topgenes"`. not sure if `ancient` is correct
    conda:
        "llava5"
    output:
        all_perplexities=PROJECT_DIR / config["paths"]["llava"]["evaluation_results"] / "all_perplexities.csv",
    params:
        num_projector_tokens=int(config["llava_projector_type"].split("_")[1].strip("t")),
        background_shuffle=lambda wildcards: "genesshuffled" if wildcards.prompt_variation == "with50topgenesshuffled" else "transcriptome",
        num_negatives=30,
        model_layer_selector=lambda wildcards: {"cellwhisperer_clip_v1": -1, "geneformer": -2, "NONE": -1}[wildcards.model],  # NOTE would be better if we could use `None` instead of -1
        pre_prompt_topgenes=lambda wildcards: {"with50topgenes": config["llava_eval"]["pre_prompt_topgenes"], "with50topgenesshuffled": config["llava_eval"]["pre_prompt_topgenes"], "without50topgenes": None}[wildcards.prompt_variation],
        top_n_genes=50,
        is_multimodal=lambda wildcards: wildcards.model != "NONE"
    resources:
        mem_mb=400000,
        slurm=lambda wildcards: "cpus-per-task=20 gres=gpu:{gpu_type}:{num_gpus} qos={gpu_type} partition=gpu".format(
            gpu_type={LLAVA_BASE_MODEL: "a100", "Llama-3.1-8B-Instruct": "a100", "Llama-3.3-70B-Instruct": "a100"}[wildcards.base_model],  # needs 2x 80gb or 4x 40gb
            num_gpus={LLAVA_BASE_MODEL: "1", "Llama-3.1-8B-Instruct": "1", "Llama-3.3-70B-Instruct": "5"}[wildcards.base_model])
    log:
        notebook="logs/llava_evaluation_perplexity/{dataset}_{base_model}_{model}_{prompt_variation}.ipynb",
        log="logs/llava_evaluation_perplexity/{dataset}_{base_model}_{model}_{prompt_variation}.log"
    threads: 16
    notebook:
        "../notebooks/llava_evaluation_perplexity.py.ipynb"


rule llava_evaluation_perplexity_plots:
    """
    """

    input:
        all_perplexities=rules.llava_evaluation_perplexity.output.all_perplexities,
        mpl_style=ancient(PROJECT_DIR / config["plot_style"])
    output:
        log_perplexity_ratio=PROJECT_DIR / config["paths"]["llava"]["evaluation_results"] / "log_mean_perplexity.ratio",  # smaller is better log(ppl_real/ppl_neg_control)
        comparison_plot=PROJECT_DIR / config["paths"]["llava"]["evaluation_results"] / "perplexity_quantile.svg",  # barplot
        detailed_plot=PROJECT_DIR / config["paths"]["llava"]["evaluation_results"] / "detailed.svg",  # barplot
        full_supp_table=PROJECT_DIR / config["paths"]["llava"]["root"] / "{dataset}" / "{base_model}__{model}" / "quantile_stats_{prompt_variation}.xlsx"
    params:
        plot_celltypes=config["top20_lung_liver_blood_celltypes"],
        response_prefix=lambda wildcards: config["llava_eval"]["response_prefix_{}".format(
            "topgenes" if "_top50genes" in wildcards.dataset else "celltype")]
    conda:
        "llava5"  # newer version of pandas in this env
    log:
        notebook="logs/llava_evaluation_perplexity_plots/{dataset}_{base_model}_{model}_{prompt_variation}.ipynb"
    notebook:
        "../notebooks/llava_evaluation_perplexity_plots.py.ipynb"
