"""
Processing pipeline for generating cellxgene-ready datasets
"""

import subprocess
PROJECT_DIR = Path(subprocess.check_output("git rev-parse --show-toplevel", shell=True).decode("utf-8").strip())
configfile: PROJECT_DIR / "config.yaml"

CLIP_MODEL = config["model_name_path_map"]["cellwhisperer"]
LLAVA_BASE_MODEL = config["model_name_path_map"]["llava_base_llm"]

GPU_TYPE = "a100"
# GPU_TYPE = "a100-sxm4-80gb"

include: "../shared/rules/download_models.smk"
include: "../shared/rules/genesets.smk"
include: "../shared/rules/dataset_processing.smk"
include: "rules/prepare_cellxgene_dataset.smk"


rule all:
    input:
        expand(rules.compile_h5ad.output["adata"], dataset=config["datasets"], model=CLIP_MODEL),
    default_target: True

