"""
Processing pipeline for generating cellxgene-ready datasets
"""

PROJECT_DIR = Path(workflow.basedir).resolve().parents[1]
configfile: PROJECT_DIR / "config.yaml"

CLIP_MODEL = config["model_name_path_map"]["cellwhisperer"]
LLAVA_BASE_MODEL = config["model_name_path_map"]["llava_base_llm"]

# GPU_TYPE = "a100"
GPU_TYPE = "a100-sxm4-80gb"

include: "../shared/rules/dataset_processing.smk"
include: "rules/prepare_cellxgene_dataset.smk"

rule all:
    input:
        expand(rules.compile_h5ad.output["adata"], dataset=config["datasets"], model=CLIP_MODEL),
    default_target: True

