"""
Processing pipeline for generating cellxgene-ready datasets
"""

PROJECT_DIR = Path(workflow.basedir).resolve().parents[1]
configfile: PROJECT_DIR / "config.yaml"

CLIP_MODEL = config["model_name_path_map"]["cellwhisperer"]
TARGET_DATASETS = ["daniel", "development4s_raw", "development4s_scvi"]  # config["datasets"] "tabula_sapiens", 
LLAVA_BASE_MODEL = "Mistral-7B-Instruct-v0.2"

include: "../shared/rules/dataset_processing.smk"
include: "rules/prepare_cellxgene_dataset.smk"
include: "rules/gsva_correlation.smk"  # NOTE this is a bit of an outlier in this pipeline

rule all:
    input:
        expand(rules.compile_h5ad.output["adata"], dataset=TARGET_DATASETS, model=CLIP_MODEL)

