"""
Processing pipeline for generating cellxgene-ready datasets
"""

PROJECT_DIR = Path(workflow.basedir).resolve().parents[1]
configfile: PROJECT_DIR / "config.yaml"

CLIP_MODEL = config["model_name_path_map"]["cellwhisperer"]
TARGET_DATASETS = config["datasets"]  # config["datasets"] "tabula_sapiens",
LLAVA_BASE_MODEL = "Mistral-7B-Instruct-v0.2"

# GPU_TYPE = "a100"
GPU_TYPE = "a100-sxm4-80gb"

include: "../shared/rules/dataset_processing.smk"
include: "rules/prepare_cellxgene_dataset.smk"

# Manuscript plots (consider moving this to a dedicated pipeline)
include: "rules/umap_plots.smk"
include: "rules/gsva_correlation.smk"

rule all:
    input:
        # Generate datasets for cellxgene
        expand(rules.compile_h5ad.output["adata"], dataset=TARGET_DATASETS, model=CLIP_MODEL),
        # Manuscript plots
        # rules.geo_umap_plots.output.cluster_labeled.format(model=config["model_name_path_map"]["cellwhisperer"]),
        expand(PROJECT_DIR / config["paths"]["gsva"]["correlation"],dataset=["archs4_metasra", "daniel", "tabula_sapiens"], model=CLIP_MODEL)
    default_target: True

