"""
Use `langchain` to convert structured annotations (JSON) from diverse sources into curated natural language.
"""

PROJECT_DIR = Path(workflow.basedir).resolve().parents[1]
configfile: PROJECT_DIR / "config.yaml"

DATASETS = config["datasets"]
DATASETS = ["archs4_metasra"]
RESULTS_DIR = PROJECT_DIR / "results" / "pre_training_preparation"
REPLICATES = list(range(config["num_epochs"]))
REPLICATES = [0]

include: "rules/annotation_processing.smk"
include: "rules/training_sample_weights.smk"

rule all:
    input:
        [PROJECT_DIR / config["paths"]["full_dataset"].format(dataset=dataset) for dataset in DATASETS]


rule integrate_dataset:
    input:
        read_count_table=PROJECT_DIR / config["paths"]["read_count_table"],
        processed_annotations=rules.aggregate_processed.output.multi,
        **dict(zip(["transcriptome_weights", "annotation_weights"], expand(rules.local_density_to_sample_weight.output.weight, modality=["transcriptome", "annotation"], allow_missing=True))),
    output:
        PROJECT_DIR / config["paths"]["full_dataset"]
    params:
        anndata_label_name=config["anndata_label_name"],
    conda:
        "cellwhisperer"
        # PROJECT_DIR / "envs" / "main.yaml"
    resources:
        mem_mb=300000,
    script:
        "scripts/integrate_dataset.py"
