"""
Use `langchain` to convert structured annotations (JSON) from diverse sources into curated natural language.
"""

PROJECT_DIR = Path(workflow.basedir).resolve().parents[1]
configfile: PROJECT_DIR / "config.yaml"

DATASETS = config["datasets"]
DATASETS = ["archs4_metasra"]
RESULTS_DIR = PROJECT_DIR / "results" / "pre_training_processing"
REPLICATES = list(range(config["num_replicates"]))
REPLICATES = [0, 1]

include: "rules/annotation_processing.smk"
include: "rules/training_sample_weights.smk"
include: "rules/gsva.smk"

rule all:
    input:
        [PROJECT_DIR / config["paths"]["full_dataset"].format(dataset=dataset) for dataset in DATASETS],

rule integrate_dataset:
    input:
        read_count_table=PROJECT_DIR / config["paths"]["read_count_table"],
        # gsva_csv=PROJECT_DIR / config["paths"]["gsva_results"],
        processed_annotations=ancient(rules.aggregate_processed.output.multi),
        transcriptome_weights=ancient(rules.local_density_to_sample_weight.output.weight.format(modality="transcriptome", dataset="{dataset}")),
        annotation_weights=ancient(rules.local_density_to_sample_weight.output.weight.format(modality="annotation", dataset="{dataset}")),
    output:
        PROJECT_DIR / config["paths"]["full_dataset"]
    params:
        anndata_label_name=config["anndata_label_name"],
    conda:
        "cellwhisperer"
        # PROJECT_DIR / "envs" / "main.yaml"
    resources:
        mem_mb=300000,
    script:
        "scripts/integrate_dataset.py"
