version: '3.8'
services:
  cellwhisperer_clip:
    build: .
    runtime: nvidia
    working_dir: /opt/cellwhisperer
    volumes:
      - ./docker_conda:/opt/miniconda3
      - ./start.sh:/start.sh
      - ~/cellwhisperer:/opt/cellwhisperer
      - ~/cellwhisperer/results/models/jointemb/03jujd8s.ckpt:/model.ckpt
      - cache:/cache/
    command: /bin/bash /start.sh python src/model_server/main.py
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      NVIDIA_VISIBLE_DEVICES: GPU-c38cbc2d-129a-dddf-9ed4-8a0e06763d33
      MODEL: "/model.ckpt"
      CONDA_ENV: cellwhisperer
      TRANSFORMERS_CACHE: /cache/transformers  # soon deprecated in favor of HF_CACHE
      HF_CACHE: /cache/transformers
      CELLWHISPERER_CACHE: /cache/cellwhisperer
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia

  cellwhisperer_llava_controller:  &llava-service
    stdin_open: true
    tty: true
    runtime: nvidia
    working_dir: /opt/cellwhisperer
    volumes:
      - ./docker_conda:/opt/miniconda3
      - ./start.sh:/start.sh
      - ~/cellwhisperer:/opt/cellwhisperer
    environment:
      CONDA_ENV: llava
    build: .
    command: /bin/bash /start.sh python -m llava.serve.controller --host 0.0.0.0 --port 10000

  cellwhisperer_llava_model:
    <<: *llava-service
    command: /bin/bash /start.sh python -m llava.serve.model_worker --multi-modal --host 0.0.0.0 --controller http://cellwhisperer_llava_controller:10000 --port 40000 --worker http://cellwhisperer_llava_model:40000 --model-path /Mistral-7B-Instruct-v0.2__03jujd8s/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
    volumes:
      - ./docker_conda:/opt/miniconda3
      - ./start.sh:/start.sh
      - ~/cellwhisperer:/opt/cellwhisperer
      - ~/cellwhisperer/results/llava/finetuned/Mistral-7B-Instruct-v0.2__03jujd8s:/Mistral-7B-Instruct-v0.2__03jujd8s  # the name is important
      - cache:/cache/
    environment:
      NVIDIA_VISIBLE_DEVICES: GPU-c38cbc2d-129a-dddf-9ed4-8a0e06763d33
      CONDA_ENV: llava
      HF_CACHE: /cache/transformers

  # cellwhisperer_llava_server:
  #   <<: *llava-service
  #   command: /bin/bash /start.sh python -m llava.serve.gradio_web_server --controller http://cellwhisperer_llava_controller:10000 --model-list-mode reload

  cellxgene_tabsap: &cellxgene-service
    build: .
    working_dir: /opt/cellwhisperer
    volumes:
      - ./docker_conda:/opt/miniconda3
      - ./start.sh:/start.sh
      - ~/cellwhisperer:/opt/cellwhisperer
      - ~/cellwhisperer/results/tabula_sapiens/03jujd8s/cellxgene.h5ad:/dataset.h5ad
      - ./llava_logs/tabsap/:/logs/
    # TODO add --debug here if more debug info is needed
    command: /bin/bash /start.sh cellxgene launch -v -p 5005  --host 0.0.0.0 --max-category-items 500 --backed /dataset.h5ad  "http://cellwhisperer_clip:8910/api"
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      NVIDIA_VISIBLE_DEVICES: GPU-c38cbc2d-129a-dddf-9ed4-8a0e06763d33
      # CXG_CLIENT_PORT: 3000
      CXG_OPTIONS: "--host 0.0.0.0 --max-category-items 500 --backed"
      CXG_SERVER_PORT: 5005
      DATASET: "/dataset.h5ad"
      LOGDIR: "/logs/"
      MODEL: "http://cellwhisperer_clip:8910/api"
      JEST_ENV: "prod"
      RETRY_ATTEMPTS: 2
      CONDA_ENV: cellwhisperer
    deploy:
      resources:
        limits:
          memory: 16G

  cellxgene_daniel:
    <<: *cellxgene-service
    volumes:
      - ./docker_conda:/opt/miniconda3
      - ./start.sh:/start.sh
      - ~/cellwhisperer:/opt/cellwhisperer
      - ~/cellwhisperer/results/daniel/03jujd8s/cellxgene.h5ad:/dataset.h5ad
      - ./llava_logs/daniel/:/logs/

  cellxgene_daniel_dev:
    <<: *cellxgene-service
    command:
      /bin/bash /start.sh source /dev_server.sh
    volumes:
      - ./docker_conda:/opt/miniconda3
      - ./start.sh:/start.sh
      - ./dev_server.sh:/dev_server.sh
      - ~/cellwhisperer:/opt/cellwhisperer
      - ~/cellwhisperer/results/daniel/03jujd8s/cellxgene.h5ad:/dataset.h5ad
      - ./llava_logs/daniel_dev/:/logs/
    ports:
      - "3000:3000"
      - "5005:5005"

  cellxgene_development_scvi:
    <<: *cellxgene-service
    volumes:
      - ./docker_conda:/opt/miniconda3
      - ./start.sh:/start.sh
      - ~/cellwhisperer:/opt/cellwhisperer
      - ~/cellwhisperer/results/development4s_scvi/03jujd8s/cellxgene.h5ad:/dataset.h5ad
      - ./llava_logs/development_scvi/:/logs/

  cellxgene_development_raw:
    <<: *cellxgene-service
    volumes:
      - ./docker_conda:/opt/miniconda3
      - ./start.sh:/start.sh
      - ~/cellwhisperer:/opt/cellwhisperer
      - ~/cellwhisperer/results/development4s_raw/03jujd8s/cellxgene.h5ad:/dataset.h5ad
      - ./llava_logs/development_raw/:/logs/

  cellxgene_geo:
    <<: *cellxgene-service
    volumes:
      - ./docker_conda:/opt/miniconda3
      - ./start.sh:/start.sh
      - ~/cellwhisperer:/opt/cellwhisperer
      - ~/cellwhisperer/results/archs4_metasra/03jujd8s/cellxgene.h5ad:/dataset.h5ad
      - ./llava_logs/geo/:/logs/

  cellxgene_car_t:
    <<: *cellxgene-service
    volumes:
      - ./docker_conda:/opt/miniconda3
      - ./start.sh:/start.sh
      - ~/cellwhisperer:/opt/cellwhisperer
      - ~/cellwhisperer/results/car_t/03jujd8s/cellxgene.h5ad:/dataset.h5ad
      - ./llava_logs/car_t/:/logs/

  cellxgene_hcaorganoids_cancer__organoid:
    <<: *cellxgene-service
    volumes:
      - ./docker_conda:/opt/miniconda3
      - ./start.sh:/start.sh
      - ~/cellwhisperer:/opt/cellwhisperer
      - ~/cellwhisperer/results/hcaorganoids_cancer__organoid/03jujd8s/cellxgene.h5ad:/dataset.h5ad
      - ./llava_logs/hcaorganoids_cancer__organoid/:/logs/
  cellxgene_hcaorganoids_cancer__primary:
    <<: *cellxgene-service
    volumes:
      - ./docker_conda:/opt/miniconda3
      - ./start.sh:/start.sh
      - ~/cellwhisperer:/opt/cellwhisperer
      - ~/cellwhisperer/results/hcaorganoids_cancer__primary/03jujd8s/cellxgene.h5ad:/dataset.h5ad
      - ./llava_logs/hcaorganoids_cancer__primary/:/logs/

  cellxgene_hcaorganoids_normal__primary:
    <<: *cellxgene-service
    volumes:
      - ./docker_conda:/opt/miniconda3
      - ./start.sh:/start.sh
      - ~/cellwhisperer:/opt/cellwhisperer
      - ~/cellwhisperer/results/hcaorganoids_normal__primary/03jujd8s/cellxgene.h5ad:/dataset.h5ad
      - ./llava_logs/hcaorganoids_normal__primary/:/logs/

  cellxgene_hcaorganoids_normal__organoid:
    <<: *cellxgene-service
    volumes:
      - ./docker_conda:/opt/miniconda3
      - ./start.sh:/start.sh
      - ~/cellwhisperer:/opt/cellwhisperer
      - ~/cellwhisperer/results/hcaorganoids_normal__organoid/03jujd8s/cellxgene.h5ad:/dataset.h5ad
      - ./llava_logs/hcaorganoids_normal__organoid/:/logs/

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - cellxgene_tabsap
      - cellxgene_geo
      - cellxgene_development_raw
      - cellxgene_development_scvi
      - cellxgene_daniel
      # ...
    restart: unless-stopped


  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      # - "start"  # tried to start with config but did not work
      # - "--all"
      - "http"
      - "nginx:80"
      - "--basic-auth"
      - "review:iclr2024-mlgenx"
      - "--domain"
      - "upright-communal-panda.ngrok-free.app"
      - "--config"
      - "/etc/ngrok.yml" # ,/ngrok.yml"
    volumes:
      - ~/.config/ngrok/ngrok.yml:/etc/ngrok.yml
      # - ./ngrok.yml:/ngrok.yml
    ports:
      - 4040:4040

volumes:
  cache:
