# add these wo lines to the services for debugging
# - ./docker_conda:/opt/miniconda3
# - ~/cellwhisperer:/opt/cellwhisperer


version: '3.8'
services:
  cellwhisperer_clip:
    build:
      context: ../..
    image: cellwhisperer
    runtime: nvidia
    working_dir: /opt/cellwhisperer
    volumes:
      - ~/cellwhisperer/results/models/jointemb/cellwhisperer_clip_v1.ckpt:/model.ckpt
      - cache:/cache/
      - ~/cellwhisperer:/opt/cellwhisperer
    command: python src/model_server/main.py
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      NVIDIA_VISIBLE_DEVICES: GPU-c38cbc2d-129a-dddf-9ed4-8a0e06763d33
      MODEL: "/model.ckpt"
      CONDA_ENV: cellwhisperer
      TRANSFORMERS_CACHE: /cache/transformers  # soon deprecated in favor of HF_CACHE
      HF_CACHE: /cache/transformers
      CELLWHISPERER_CACHE: /cache/cellwhisperer
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia

  cellwhisperer_llava_controller:  &llava-service
    stdin_open: true
    tty: true
    runtime: nvidia
    working_dir: /opt/cellwhisperer
    environment:
      CONDA_ENV: llava
    build:
      context: ../..
    image: cellwhisperer
    command: python -m llava.serve.controller --host 0.0.0.0 --port 10000

  cellwhisperer_llava_model:
    <<: *llava-service
    command: python -m llava.serve.model_worker --multi-modal --host 0.0.0.0 --controller http://cellwhisperer_llava_controller:10000 --port 40000 --worker http://cellwhisperer_llava_model:40000 --model-path /Mistral-7B-Instruct-v0.2__cellwhisperer_clip_v1/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
    volumes:
      - ~/cellwhisperer/results/llava/finetuned/Mistral-7B-Instruct-v0.2__cellwhisperer_clip_v1:/Mistral-7B-Instruct-v0.2__cellwhisperer_clip_v1:ro  # the name is important
      - cache:/cache/
    environment:
      NVIDIA_VISIBLE_DEVICES: GPU-c38cbc2d-129a-dddf-9ed4-8a0e06763d33
      CONDA_ENV: llava
      HF_CACHE: /cache/transformers

  # cellwhisperer_llava_server:
  #   <<: *llava-service
  #   command: /bin/bash /start.sh python -m llava.serve.gradio_web_server --controller http://cellwhisperer_llava_controller:10000 --model-list-mode reload

  cellxgene_tabsap: &cellxgene-service
    build:
      context: ../..
    image: cellwhisperer
    working_dir: /opt/cellwhisperer
    volumes:
      - ~/cellwhisperer/results/tabula_sapiens/cellwhisperer_clip_v1/cellxgene.h5ad:/dataset.h5ad:ro
      - ~/cellwhisperer/hosting/home/cellxgene_config.yaml:/cellxgene_config.yaml:ro
      - ./llava_logs/tabsap/:/logs/
      - ~/cellwhisperer:/opt/cellwhisperer
    command: gunicorn --worker-class gevent --bind 0.0.0.0:5005 server.app.wsgi:application --timeout 60
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      CXG_CONFIG_FILE: /cellxgene_config.yaml
      NVIDIA_VISIBLE_DEVICES: GPU-c38cbc2d-129a-dddf-9ed4-8a0e06763d33
      LOGDIR: "/logs/"
      MODEL: "http://cellwhisperer_clip:8910/api"
      JEST_ENV: "prod"
      RETRY_ATTEMPTS: 2
      CONDA_ENV: cellwhisperer
    deploy:
      resources:
        limits:
          memory: 16G
    depends_on:
      - cellwhisperer_clip
      - cellwhisperer_llava_model
      - cellwhisperer_llava_controller

  cellxgene_daniel:
    <<: *cellxgene-service
    volumes:
      - ~/cellwhisperer/hosting/home/cellxgene_config.yaml:/cellxgene_config.yaml:ro
      - ~/cellwhisperer/results/daniel/cellwhisperer_clip_v1/cellxgene.h5ad:/dataset.h5ad:ro
      - ./llava_logs/daniel/:/logs/
      - ~/cellwhisperer:/opt/cellwhisperer
    # ports:
      # - "5005:5005"  # for testing without nginx
    # command: cellxgene launch -v -p 5005  --host 0.0.0.0 --max-category-items 500 --var-names gene_name --debug --backed /dataset.h5ad  "http://cellwhisperer_clip:8910/api" --debug

  cellxgene_development_scvi:
    <<: *cellxgene-service
    volumes:
      - ~/cellwhisperer/results/development_merged5000/cellwhisperer_clip_v1/cellxgene.h5ad:/dataset.h5ad:ro
      - ~/cellwhisperer/hosting/home/cellxgene_config.yaml:/cellxgene_config.yaml:ro
      - ./llava_logs/development_scvi/:/logs/
      - ~/cellwhisperer:/opt/cellwhisperer

  cellxgene_development_raw:
    <<: *cellxgene-service
    volumes:
      - ~/cellwhisperer/results/development4s_raw/cellwhisperer_clip_v1/cellxgene.h5ad:/dataset.h5ad:ro
      - ~/cellwhisperer/hosting/home/cellxgene_config.yaml:/cellxgene_config.yaml:ro
      - ./llava_logs/development_raw/:/logs/
      - ~/cellwhisperer:/opt/cellwhisperer

  cellxgene_geo:
    <<: *cellxgene-service
    volumes:
      - ~/cellwhisperer/results/archs4_metasra/cellwhisperer_clip_v1/cellxgene.h5ad:/dataset.h5ad:ro
      - ~/cellwhisperer/hosting/home/cellxgene_config.yaml:/cellxgene_config.yaml:ro
      - ./llava_logs/geo/:/logs/
      - ~/cellwhisperer:/opt/cellwhisperer
    deploy:
      resources:
        limits:
          memory: 20G

  cellxgene_car_t:
    <<: *cellxgene-service
    volumes:
      - ~/cellwhisperer/results/car_t/cellwhisperer_clip_v1/cellxgene.h5ad:/dataset.h5ad:ro
      - ~/cellwhisperer/hosting/home/cellxgene_config.yaml:/cellxgene_config.yaml:ro
      - ./llava_logs/car_t/:/logs/
      - ~/cellwhisperer:/opt/cellwhisperer

  cellxgene_bowel_disease:
    <<: *cellxgene-service
    volumes:
      - ~/cellwhisperer/results/bowel_disease/cellwhisperer_clip_v1/cellxgene.h5ad:/dataset.h5ad:ro
      - ~/cellwhisperer/hosting/home/cellxgene_config.yaml:/cellxgene_config.yaml:ro
      - ./llava_logs/bowel_idisease/:/logs/
      - ~/cellwhisperer:/opt/cellwhisperer

  # cellxgene_hcaorganoids_cancer__organoid:
  #   <<: *cellxgene-service
  #   volumes:
  #     - ~/cellwhisperer/results/hcaorganoids_cancer__organoid/cellwhisperer_clip_v1/cellxgene.h5ad:/dataset.h5ad:ro
  #     - ./llava_logs/hcaorganoids_cancer__organoid/:/logs/
  #     - ~/cellwhisperer:/opt/cellwhisperer
  # cellxgene_hcaorganoids_cancer__primary:
  #   <<: *cellxgene-service
  #   volumes:
  #     - ~/cellwhisperer/results/hcaorganoids_cancer__primary/cellwhisperer_clip_v1/cellxgene.h5ad:/dataset.h5ad:ro
  #     - ./llava_logs/hcaorganoids_cancer__primary/:/logs/
  #     - ~/cellwhisperer:/opt/cellwhisperer

  # cellxgene_hcaorganoids_normal__primary:
  #   <<: *cellxgene-service
  #   volumes:
  #     - ~/cellwhisperer/results/hcaorganoids_normal__primary/cellwhisperer_clip_v1/cellxgene.h5ad:/dataset.h5ad:ro
  #     - ./llava_logs/hcaorganoids_normal__primary/:/logs/
  #     - ~/cellwhisperer:/opt/cellwhisperer

  # cellxgene_hcaorganoids_normal__organoid:
  #   <<: *cellxgene-service
  #   volumes:
  #     - ~/cellwhisperer/results/hcaorganoids_normal__organoid/cellwhisperer_clip_v1/cellxgene.h5ad:/dataset.h5ad:ro
  #     - ./llava_logs/hcaorganoids_normal__organoid/:/logs/
  #     - ~/cellwhisperer:/opt/cellwhisperer

  cellxgene_gut_cell_atlas:
    <<: *cellxgene-service
    volumes:
      - ~/cellwhisperer/results/gut_cell_atlas/cellwhisperer_clip_v1/cellxgene.h5ad:/dataset.h5ad:ro
      - ~/cellwhisperer/hosting/home/cellxgene_config.yaml:/cellxgene_config.yaml:ro
      - ./llava_logs/gut_cell_atlas/:/logs/
      - ~/cellwhisperer:/opt/cellwhisperer

  # certificate renewal is run through my nixos configuration
  nginx:
    image: nginx:latest
    volumes:
      - ./htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - cellxgene_tabsap
      - cellxgene_geo
      - cellxgene_development_raw
      - cellxgene_development_scvi
      - cellxgene_daniel
      - cellxgene_car_t
      - cellxgene_bowel_disease
      - cellxgene_gut_cell_atlas
      # ...
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx

volumes:
  cache:
