
events {}

http {
    server {
        listen 80;
        root /static;

        # Serve 'index.html' for root URL, '/index', and '/index.html'
        location = / {
            try_files /index.html =404;
        }

        location = /index {
            try_files /index.html =404;
        }

        location = /index.html {
            try_files /index.html =404;
        }

        location /tabulasapiens/ {
            proxy_pass http://cellxgene_tabsap:5005/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /geo/ {
            proxy_pass http://cellxgene_geo:5005/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /daniel/ {
            proxy_pass http://cellxgene_daniel:5005/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /development_raw/ {
            proxy_pass http://cellxgene_development_raw:5005/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /development_scvi/ {
            proxy_pass http://cellxgene_development_scvi:5005/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /car_t/ {
            proxy_pass http://cellxgene_car_t:5005/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /hcaorganoids_normal__organoid/ {
            proxy_pass http://cellxgene_hcaorganoids_cancer__organoid:5005/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /hcaorganoids_normal__primary/ {
            proxy_pass http://cellxgene_hcaorganoids_normal__primary:5005/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /hcaorganoids_cancer__organoid/ {
            proxy_pass http://cellxgene_hcaorganoids_cancer__organoid:5005/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /hcaorganoids_cancer__primary/ {
            proxy_pass http://cellxgene_hcaorganoids_normal__primary:5005/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}

