"""
"""

# snakemake remote HTTP object
from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider
import glob
import pandas as pd


PROJECT_DIR = Path(workflow.basedir).resolve().parents[1]
configfile: PROJECT_DIR / "config.yaml"

HTTP = HTTPRemoteProvider()


GPU_TYPE = "a100"
# GPU_TYPE = "a100-sxm4-80gb"  # used for the data_processing and conversation generation rules
CLIP_MODEL = config["model_name_path_map"]["cellwhisperer"]
PROJECTOR_TYPE = "mlp2x_8t_gelu"  # TODO fails if > 8 (12 and 16 both failed. either due to  dual-digit not being ok or because they become too large for some reason ). Here is the error evoked (can use pdb to trace (breakpoint before beaks)): /msc/home/mschae83/miniconda3/envs/llava2/lib/python3.10/site-packages/torch/nn/utils/clip_grad.py(55)


# random sample (n=100) of the GSVA datasets (which are already weight-corrected)
# TODO: weight correction for archs4 only used the transcriptome- not the annotation-embeddings. Due to this however, there are some single cells in here, which can count as data leakage. Solution: Take single_cell_probability > 0.2 and eliminate these samples in TEST_IDS.
TEST_IDS = pd.read_csv("./test_ids", header=None).iloc[:, 0].to_list()

# For snakemake efficiency, extract the samples once and store them
if not os.path.exists("./tmp_gsva_samples.csv"):
    ARCHS4_GSVA_SAMPLES = pd.read_parquet(PROJECT_DIR / config["paths"]["gsva"]["result"].format(dataset="archs4_metasra")).set_index("Unnamed: 0").drop(columns=["library"]).columns
    # store GSVA samples
    with open("./tmp_gsva_samples.csv", "w") as f:
        f.write("\n".join(ARCHS4_GSVA_SAMPLES.to_list()))
else:
    ARCHS4_GSVA_SAMPLES = pd.read_csv("./tmp_gsva_samples.csv", header=None).iloc[:, 0]

NUM_COMPLEX_SAMPLES = 5000
NUM_DETAILED_SAMPLES = 10000
CONVERSATION_START = NUM_COMPLEX_SAMPLES + NUM_DETAILED_SAMPLES
COMPLEX_SAMPLES = ARCHS4_GSVA_SAMPLES.to_list()[:NUM_COMPLEX_SAMPLES]
DETAILED_SAMPLES = ARCHS4_GSVA_SAMPLES.to_list()[NUM_COMPLEX_SAMPLES:CONVERSATION_START]
scattergather:
    split=128



MODELS= [
    # "locking_mode_UU_0_0.0001_x5p78fy7",  # is 'UU' better? # TODO loading fails, because the 'UU' is not properly recognized and the transcriptome part is 'locked away', leading to 'Unexpected key(s) in state_dict: "model.transcriptome_model.geneformer_model.bert.encoder.layer.6.attention.self.query.weight",....'
    "cellwhisperer_clip_v1",  # old, as baseline # functions as 'no-cellxgene'
    config["model_name_path_map"]["cellwhisperer"],
    "no_archs4_data_42_0.0005_09cid8z6"  # does GEO data improve conversation ability? (I guess we would need a disease-centric validation set for this...)
]

# TODO archs4_metasra is actually a combination of archs4 and tabsap. I should rename it here (and everywhere)!
rule all:
    input:
        expand(PROJECT_DIR / config["paths"]["llava"]["evaluation_results"] / "comparison.svg",
               dataset=["archs4_metasra", "tabula_sapiens"],  # these are evaluation-datasets here!
               base_model=["Mistral-7B-Instruct-v0.2"],  # TODO test as well: "BioMistral-7B", "BioMistral-7B-DARE",
               model=MODELS
               ),
        expand(PROJECT_DIR / config["paths"]["llava"]["evaluation_results"] / "generation_gpt4_review_summary.svg",
               dataset=["archs4_metasra"],  # these are evaluation-datasets here!  # TODO evaluation of tabula_sapiens dataset only makes sense if I provide another judgement prompt
               base_model=["Mistral-7B-Instruct-v0.2"],  # TODO test as well: "BioMistral-7B", "BioMistral-7B-DARE",
               model=MODELS
               ),

    default_target: True

include: "../shared/rules/dataset_processing.smk"
include: "rules/dataset.smk"
include: "rules/training.smk"
include: "rules/evaluation.smk"
