"""
Snakefile to generate RNA (transcriptome) embeddings
"""
from pathlib import Path

PROJECT_DIR = Path(workflow.basedir).resolve().parents[1]
configfile: PROJECT_DIR / "config.yaml"


RESULTS_DIR = PROJECT_DIR / "results" / "rna" / "geneformer" / "{dataset}"


rule all:
    input:
        expand(PROJECT_DIR / config["paths"]["rna_embeddings"], dataset=config["datasets"])
rule prepare_data_loom:
    input:
        PROJECT_DIR / config["paths"]["read_count_table"]
    output:
        RESULTS_DIR / "read_count_table.loom"
    conda:
        PROJECT_DIR / "envs" / "main.yaml"
    script:
        "scripts/prepare_data_loom.py"

rule geneformer_tokenizing:
    """
    Tokenize the transcriptomes
    """
    input:
        RESULTS_DIR / "read_count_table.loom"
    output:
        directory(RESULTS_DIR / "tokens.dataset")
    conda:
        PROJECT_DIR / "envs" / "main.yaml"
    script:
        "scripts/geneformer_tokenizing.py"

rule download_model:
    output:
        directory(PROJECT_DIR / "resources" / "geneformer-12L-30M" )
    shell: """
    mkdir -p {output[0]}
    cd {output[0]}
    wget https://huggingface.co/ctheodoris/Geneformer/resolve/main/geneformer-12L-30M/pytorch_model.bin
    wget https://huggingface.co/ctheodoris/Geneformer/resolve/main/geneformer-12L-30M/config.json
    """

rule geneformer_embeddings:
    """
    Use Geneformer model to generate transcriptome embeddings
    """
    input:
        tokens_directory=directory(RESULTS_DIR / "tokens.dataset"),
        model_path=PROJECT_DIR / "resources" / "geneformer-12L-30M" 
    output:
        PROJECT_DIR / config["paths"]["rna_embeddings"]
    conda:
        PROJECT_DIR / "envs" / "main.yaml"
    script:
        "scripts/geneformer_embeddings.py"
