#!/bin/bash

TOTAL_NUM_JOBS=20
NUM_SIMULT_JOBS=1

gpu_type="a100-sxm4-80gb"

JOBID=$(sbatch --array=0-$((TOTAL_NUM_JOBS-1))%${NUM_SIMULT_JOBS} --mem 200GB -N 1 -q $gpu_type --partition gpu --gres gpu:${gpu_type}:1 --ntasks-per-node=1 -c 30 /msc/home/mschae83/single-cellm/src/pre_training_processing/misc/start_llm_slurm_helper.sh | awk '{print $4}')

echo $JOBID

function slurm_log() {
    logfile=$(scontrol show jobid $1 | grep -oP 'StdOut=\K\S+')
    less +F $logfile
}


slurm_log $JOBID
