"""
Use `langchain` to convert structured annotations (JSON) from diverse sources into curated natural language.
"""

PROJECT_DIR = Path(workflow.basedir).resolve().parents[2]
configfile: PROJECT_DIR / "config.yaml"

DATASETS = config["datasets"].keys()

PROCESSED_FILE = PROJECT_DIR / "results" / "annotation_processing" / "processed" / "{dataset}" / "{sample_id}.txt"


def annotation_ids(wildcards):
    """
    Return the paths to all the annotations for a given dataset.
    """
    import json
    with open(PROJECT_DIR / config["paths"]["structured_annotations"].format(dataset=wildcards.dataset)) as f:
        annotations = json.load(f)
    return [str(PROCESSED_FILE).format(sample_id=sample_id, dataset=wildcards.dataset) for sample_id in annotations.keys()]

rule all:
    input:
        [PROJECT_DIR / config["paths"]["processed_annotations"].format(dataset=dataset) for dataset in config["datasets"].keys()]

rule prepare_requests:
    """
    Open the structured annotations dataframe and extract the sample with the appropriate ID
    """
    input:
        structured_annotations = lambda wildcards: PROJECT_DIR / config["paths"]["structured_annotations"].format(dataset=wildcards.dataset),
    output:
        request = PROJECT_DIR / "results" / "annotation_processing"  / "requests" / "{dataset}" / "{sample_id}.json",
    run:
        import json

        with open(input.structured_annotations) as f:
            annotations = json.load(f)

        sample = annotations[wildcards.sample_id]
        with open(output[0], "w") as f:
            json.dump(sample, f, indent=4)

rule process_annotation:
    input:
        human_message = rules.prepare_requests.output[0],
        system_message = "prompts/process_annotations.txt",
    output:
        processed_annotation = protected(PROCESSED_FILE),  # I marked this as protected as it might be costly to produce
    conda:
        PROJECT_DIR / "envs" / "main.yaml"
    script:
        "scripts/process_annotations.py"


rule aggregate_processed:
    """
    Read in all the generated annotations and aggregate them into a single JSON file.
    """
    input:
        processed_annotations=annotation_ids
    output:
        PROJECT_DIR / config["paths"]["processed_annotations"]
    script:
        "scripts/aggregate_processed.py"
